### ISSUE TITLE
您好，我看到有在huggingface上提问，想继续请教您关于您问题后续的解决。

### ISSUE THREAD

**Issue by csliangchen** [zysNLP/machine-learning#1]
大佬，我看到你有在huggingface上问如何离线加载roberta的预训练模型的问题，关于把from_pretrained改为自己下载好的路径，请问最后是在代码的哪个文件修改后起作用了呢？我在run_multiplechioce里改是不起作用的，在model_roberta也没有找到比较好的修改的地方。
冒昧打扰，因为问题已关闭，且在您主页没有看到邮箱，只能在这里留言了~

**Comment by zysNLP** [comment]
哈哈，大佬谈不上，这个from_pretrained()只需要接你的bert模型的文件夹的路径就行，例如你的文件夹名字bert_torch_models里面需要有几个文件：pytorch_model.bin、vocab.json、config.json下载地址分别是
https://s3.amazonaws.com/models.huggingface.co/bert/roberta-large-config.json
https://s3.amazonaws.com/models.huggingface.co/bert/roberta-large-vocab.json
https://s3.amazonaws.com/models.huggingface.co/bert/roberta-large-pytorch_model.bin
好像还有个txt文件我明天给你看看

RobertaModel.from_pretrained(bert_torch_models)就可以了，不行的话再留言给我。
至于你说的在哪儿改的，我没有动任何transformers源代码，只是在自己需要的模型中加载
RobertaModel.from_pretrained(bert_torch_models)时，为了解决在终端下载速度较慢的问题。在网页中下载这些东西，有VPN还是挺快的。你的run_multiplechioce我不知道指的是什么

**Comment by csliangchen** [comment]
很感谢您回复我~
昨天我在尝试的时候，确实前半部分做的和您比较类似，根据网址下载了四个文件（roberta-base-config.json、roberta-base-merges.txt、roberta-base-pytorch_model.bin、roberta-base-vocab.json），把这几个一起放在了roberta-base文件夹里面。然后我开始修改路径，因为我是在做多选的阅读理解，所以用的是./examples/run_multiple_choice.py这个程序，我是这样修改的：
`config = config_class.from_pretrained("/mnt/data/liangchen/transformers/roberta-base/",    
                                      num_labels=num_labels,
                                          finetuning_task=args.task_name,
                                          cache_dir=args.cache_dir if args.cache_dir else None)`
然后就会提示该路径不存在预训练模型，我又去看了./transformers/modeling_roberta.py这个程序，发现也没有太好的修改的路径。所以就很想知道您加载模型的设置是怎么实现的。
再次感谢您百忙之中的回复！

**Comment by zysNLP** [comment]
我刚试了一下你的代码，没啥问题
唯一和你不同的是，你的文件夹里的文件名字跟我不同。我的也是RoBerta的模型，但是名字中没带roberta，四个名字分别是：config.json  merges.txt  pytorch_model.bin  vocab.json
你先试下改名字能不能行，我执行了：
from transformers import (WEIGHTS_NAME, BertConfig,
                                  BertForMultipleChoice, BertTokenizer,
                                  XLNetConfig, XLNetForMultipleChoice,
                                  XLNetTokenizer, RobertaConfig,
                                  RobertaForMultipleChoice, RobertaTokenizer)
MODEL_CLASSES = {
    'bert': (BertConfig, BertForMultipleChoice, BertTokenizer),
    'xlnet': (XLNetConfig, XLNetForMultipleChoice, XLNetTokenizer),
    'roberta': (RobertaConfig, RobertaForMultipleChoice, RobertaTokenizer)
}
config_class, model_class, tokenizer_class = MODEL_CLASSES[‘roberta’]
model_path = my_models_dir #我的文件夹路径
model = model_class.from_pretrained(model_path)
config = config_class.from_pretrained(model_path)
tokenizer = tokenizer_class.from_pretrained(model_path)
都没报错，不同的是，括号里面的参数我一个没加，只是加载模型

**Comment by csliangchen** [comment]
原来是名字前缀的问题，我改成不带roberta-base就好了。昨天让我搞了大半天，太谢谢您了！！！orzzzz

**Comment by zysNLP** [comment]
确实有点坑，哈哈
